name: ql_moifood_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Illustrations/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/static/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Bold.ttf
          weight: 700
